#!/bin/sh

INSTDIR='/tmp/install'
SRCDIR_SOURCE="/mnt"

check_yn() {
   YN=""
   while [ "$YN" = "" ]; do
         echo -n "$@"
         read YN
         [ "$YN" = "y" ] && YN="Y"
         [ "$YN" = "n" ] && YN="N"
         [ "$YN" = "Y" ] || [ "$YN" = "N" ] || YN=""
   done
}

abort() {
   umount $INSTDIR > /dev/null 2&>1 
   rm -rf $INSTDIR
   umount /mnt > /dev/null 2&>1 
   echo
   echo "[0;31mInstalation Aborted. Press [ENTER][0m"
   echo
   read junk
   exit
}

echo "[0;32m           ==================================[0m"
echo "[0;32m           |       SmartRouter Project      |[0m" 
echo "[0;32m           ==================================[0m"
echo
echo
echo "[0;33m           ++++++++++++++++++++++++++++++++++[0m"
echo "[0;33m           +        System Installer        +[0m"
echo "[0;33m           ++++++++++++++++++++++++++++++++++[0m"
echo 
echo
echo 
echo "[0;31m   Attention !!![0m"
echo 
echo
echo "This software will partition and format your hard disk."
echo "If you go on any data stored on it will be permanently destroyed."
echo "I'm not responsible for any data loss or hardware damage."
echo "[0;31mUSE IT AT YOUR OWN RISK.[0m"
echo
echo

check_yn "Do you want to go ahead ? (y/n) - "
[ "$YN" = "N" ] && abort

#SMP=
#while [ "$SMP" = "" ]; do 
#      echo
#      echo "[0;33mDetect your CPU instaled:[0m"
#      CPU=`cat /proc/cpuinfo | grep "model name" | awk '{print $3}'`
#      VENDOR=`cat /proc/cpuinfo | grep "vendor id" | awk '{print $3}'`
#      echo
#      echo "Vendor = $VENDOR"
#      echo "CPU    = $CPU"
#      echo
#      echo "This system support 64 bits CPU for multiple cores"
#      echo "If your CPU model multiple cores support, choose the"
#      echo "kernel SMP for the best performance system."
#      echo
#      echo " [0;33m1) kernel single (x86)[0m"
#      echo
#      echo " [0;33m2) kernel SMP (x64)[0m"
#      echo
#      echo -n "Choose your kernel system : "
#      read junk
#      case $junk in
#           1) SMP="1" ;;
#           2) SMP="0" ;;
#           *) { echo "ERROR! Try again!"; SMP="";} ;; 
#      esac
#done
umount $INSTDIR > /dev/null 2&>1
rm -rf $INSTDIR
mkdir  $INSTDIR
mount tmpfs $INSTDIR -t tmpfs -o size=32M

echo "Reading the install media..."
. /tmp/boot.info
mount -o ro $DEVICE /mnt -t $FSTYPE > /dev/null 2&>1 || { echo "Error trying to read the install media."; abort; }

for F in `ls /mnt/*.tgz`; do
    F=`basename $F .tgz`
    echo $F >> $INSTDIR/pkg.list
done;

echo
echo "Please wait. Reading System files..."
mkdir $INSTDIR/temp
mkdir $INSTDIR/temp/config
cp ${SRCDIR_SOURCE}/*.tgz        $INSTDIR/temp        > /dev/null 2&>1 
cp ${SRCDIR_SOURCE}/SRP.dpy      $INSTDIR/temp        > /dev/null 2&>1 
cp ${SRCDIR_SOURCE}/syslinux.cfg $INSTDIR/temp        > /dev/null 2&>1 
cp ${SRCDIR_SOURCE}/linux        $INSTDIR/temp        > /dev/null 2&>1 
cp -a ${SRCDIR_SOURCE}/config/*  $INSTDIR/temp/config > /dev/null 2&>1

#if [ "$SMP" = "0" ]; then
#   cp ${SRCDIR_SOURCE}/SMP/linux        $INSTDIR/temp        > /dev/null 2&>1
#   cp ${SRCDIR_SOURCE}/SMP/modules      $INSTDIR/temp        > /dev/null 2&>1
#else
#   cp ${SRCDIR_SOURCE}/linux            $INSTDIR/temp        > /dev/null 2&>1
#fi  

umount /mnt > /dev/null 2&>1
hd=
iface=
size=
upgrade=no
format=yes
upgrade_addons=no
have_addons=no
have_obsolete=no
use_cache=no
mbs=
mbs_cache=
echo "Detecting your Hard Disks..."
echo
echo
hds=`detecthds | wc -l`
treatline() {
   type=`echo $LINE | cut -f 1 -d "#"`
   hd=`echo $LINE | cut -f 2 -d "#"`
   model=`echo $LINE | cut -f 3 -d "#"`
   size=`echo $LINE | cut -f 4 -d "#"`
   cyl=`echo $LINE | cut -f 5 -d "#"`
   head=`echo $LINE | cut -f 6 -d "#"`
   sect=`echo $LINE | cut -f 7 -d "#"`
   case $hd in
        hda) iface="Primary Master";;
        hdb) iface="Primary Slave";;
        hdc) iface="Secondary Master";;
        hdd) iface="Secondary Slave";;
        sda) iface="First Device";;
        sdb) iface="Second Device";;
        sdc) iface="Third Device";;
        sdd) iface="Fourth Device";;
        sde) iface="Fifth Device";;
        *) iface="Unknow";;
   esac
}
showhd() {
   echo $number")" $type - $iface - $size MB
   echo $model
   echo
}

case "$hds" in
   0 )
      echo "There isn't any hard disk installed in this computer"
      echo "If you plugged one already check the cables and be sure"
      echo "it was detected by the BIOS."
      echo
      abort
      ;;
   1 )
      LINE=`detecthds`
      treatline
      number=1
      showhd
      ;;
   * )
      number=0
      detecthds | while read LINE; do
                        number=$(($number+1))
                        treatline
                        showhd
                  done;
      voltar=1
      while [ "$voltar" = 1 ]; do
            echo -n "Choose the hard disk you want to install the System: "
            read junk
            numb=0
            LINE=
            echo -n > $INSTDIR/line
            detecthds | while read LINE; do
                              numb=$((numb+1))
                              [ "$numb" = "$junk" ] && echo $LINE > $INSTDIR/line
                        done;
            LINE=`cat $INSTDIR/line`
            [ -n "$LINE" ] && voltar=0
            treatline
      done;
      echo
      echo "You choose:"
      showhd
      ;;
esac

check_yn "Are you sure you want to install the System to this Hard Disk ? (y/n) - "
[ "$YN" = "N" ] && abort

device="/dev/$hd"
boot_par="$device"1

echo
echo "Trying to detect an upgradable previous version of System Linux"
echo
echo "It is normal to see some error messages here, they mean only"
echo "this HD does not have any previous system version on it"
echo
mount $boot_par /mnt -t vfat > /dev/null 2&>1
if [ $? = 0 ]; then
   version=
   if [ -e "/mnt/config/coyote.cfg" ]; then
      if [ -e "/mnt/brazilfw.dpy" ]; then
          version=`cat /mnt/brazilfw.dpy | grep "BrazilFW" | awk '{print}'`
      elif [ -e "/mnt/syslinux.dpy" ]; then
          version=`cat /mnt/syslinux.dpy | grep "BrazilFW" | awk '{print}'`
      elif [ -e "/mnt/SRP.dpy" ]; then
          version=`cat /mnt/SRP.dpy | grep "SmartRouter" | awk '{print}'`
      elif [ -e "/mnt/syslinux.dpy" ]; then
          version=`cat /mnt/syslinux.dpy | grep "SmartRouter" | awk '{print}'`
      fi
   fi
   if [ -n "$version" ]; then
      echo
      echo "[0;33m++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[0m"
      echo "[0;33m+     System Linux Version found into your device :      +[0m" 
      echo "             [0;31m $version [0m"
      echo "[0;33m++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[0m"
      echo
      echo
      echo "This hard disk contains an upgradable version of System Linux"
      echo "you can upgrade it and keep your configurations"
      echo
      check_yn "Do you want to upgrade this instalation ? (y/n) - "
      if [ "$YN" = "Y" ]; then
         echo
         echo
         echo "Now you can choose if you want to format this disk again or just"
         echo "upgrade the system files preserving your logs and cache."
         echo "  If you want to preserve the data on second partition you should not format it"
         echo "  If you want to change the size of current partitions you must format it"
         echo
         check_yn "Do you want to format this disk again ? (y/n) - "
         [ "$YN" = "N" ] && format=no

         echo
         echo "Saving current configurations..."
         mkdir $INSTDIR/upgrade
         cp -a /mnt/config/* $INSTDIR/upgrade
         [ -e /mnt/ssh_keys.tgz ] && cp /mnt/ssh_keys.tgz $INSTDIR
         rm -rf $INSTDIR/upgrade/language.gz
         echo "Done."
         echo
         upgrade=yes

         echo "Looking for obsolete add-ons"
         for F in `ls /mnt/*.tgz`; do
             F=`basename $F .tgz`
             if [ -n "`grep $F /var/lib/lrpkg/addons.obsolete`" ]; then
                echo $F >> $INSTDIR/pkg.list3
                have_obsolete=yes
             fi
         done;
         if [ "$have_obsolete" = "yes" ]; then
            echo
            echo "The following obsolete add-ons were found on current instalation"
            echo "and will be DELETED."
            cat $INSTDIR/pkg.list3
            echo
            read junk
         else
            touch $INSTDIR/pkg.list3
         fi

         echo "Looking for upgradable add-ons"
         for F in `ls /mnt/*.tgz`; do
             F=`basename $F .tgz`
             if [ -z "`grep $F $INSTDIR/pkg.list`" -a -z "`grep $F $INSTDIR/pkg.list3`" ]; then
                echo $F >> $INSTDIR/pkg.list2
                have_addons=yes
             fi
         done;
         if [ "$have_addons" = "yes" ]; then
            echo
            echo "The following upgradable add-ons were found on current instalation"
            cat $INSTDIR/pkg.list2
            echo
            check_yn "Do you want to keep them ? (y/n) - "
            if [ "$YN" = "Y" ]; then
               mkdir $INSTDIR/oldpacks
               cat $INSTDIR/pkg.list2 | while read f; do
                                              cp /mnt/$f.tgz $INSTDIR/oldpacks
                                        done;
               echo "Done."
               echo
               upgrade_addons=yes
            fi
         fi
      fi
   fi
fi
umount /mnt  > /dev/null 2&>1

if [ "$format" = "yes" ]; then
   min_part=$(($head*$sect/2048))
   echo $iface - $showsize MB
   echo $model
   sfdisk -g $device
   echo
   default_mbs=40
   [ $size -lt $default_mbs ] && default_mbs=$size
   while [ "$mbs" = "" ]; do
         echo
         echo -n "Set the size of partition to create in Megabytes (default=$default_mbs MB) : "
         read junk
         [ -z "$junk" ] && mbs=$default_mbs
         [ -n "$junk" ] && mbs=$junk
         if [ "$mbs" -lt 8 ]; then
            echo "Too little. Set at least 8 Megabytes"
            mbs=
         elif [ "$mbs" -lt $min_part ]; then
              echo "Too little. The smaller partition for this hd is $min_part Megabytes"
              mbs=
         elif [ "$mbs" -gt 1000 ]; then
              echo "Too big. Set at most 1000 Megabytes"
              mbs=
         elif [ "$mbs" -gt $size ]; then
              echo "Too big. The hd has only $size Megabytes"
              mbs=
         fi
   done;

   echo
   echo "If you are planning to install some proxy cache to this"
   echo "Smart Router you can create a second partition using the"
   echo "rest of this HD."
   echo
   check_yn "Do you want to create a second partition ? (y/n) - "
   [ "$YN" = "Y" ] && use_cache=yes

   if [ "$use_cache" = "yes" ]; then
      cyl_first=$((($mbs*1024*1024)/($head*$sect*512)))
      cyl_remaining=$(($cyl-$cyl_first))
      default_mbs_cache=$(($cyl_remaining*$head*$sect/2048))
      while [ "$mbs_cache" = "" ]; do
            echo
            echo -n "Set the size of partition to create in Megabytes (default=$default_mbs_cache MB) : "
            read junk
            [ -z "$junk" ] && mbs_cache=$default_mbs_cache
            [ -n "$junk" ] && mbs_cache=$junk
            if [ "$mbs_cache" -lt 3 ] ; then
               echo "Too little. Set at least 3 Megabytes"
       	       mbs_cache=
            elif [ "$mbs_cache" -lt $min_part ]; then
                 echo "Too little. The smaller partition for this hd is $min_part Megabytes"
                 mbs_cache=
            elif [ "$mbs_cache" -gt $default_mbs_cache ]; then
                 echo "Too big. The hd has only $default_mbs_cache Megabytes remaining"
                 mbs_cache=
            fi
      done;
      defautl_cache_par=ext2 
      echo
      while [ "$type_cache_par" = "" ]; do
            echo "[0;34m          +++++++++++++++++++++++++++++++++++++++++++++++++[0m"
            echo "[0;34m          +         Type for second partition             +[0m"
            echo "[0;34m          +++++++++++++++++++++++++++++++++++++++++++++++++[0m"
            echo
            echo "The filesystem default format second partition is ext2 (option recommended)"
            echo
            echo "Options:"
            echo
            echo "[0;33m1 ) ext2[0m"
            echo
            echo "[0;33m2 ) ext3[0m"
            echo
            echo -n "Choose the type for filesystem on second partition : "
            read junk
            if [ -z "$junk" ]; then
               { type_cache_par=$defautl_cache_par; echo "The default value (ext2) are selected."; }
            else
               case $junk in 
                    1 )
                       { type_cache_par=$defautl_cache_par; echo "The default value (ext2) are selected."; }
                       ;;
                    2 )
                       { type_cache_par=ext3; echo "The filesystem ext3 are selected."; }
                       ;;
                    * )
                       { type_cache_par=$defautl_cache_par; echo "The default value (ext2) are selected."; }
                       ;;
               esac
            fi
      done;      
   fi
   echo
   echo
   echo "[0;33m          ###############################################[0m"
   echo "[0;33m          #                 ATTENTION !!!               #[0m"
   echo "[0;33m          ###############################################[0m"
   echo
   echo "This hard disk will be partitioned and formated now."
   echo "If you go on any data stored on it will be permanently destroyed."
   echo
   check_yn "Are you sure you want to do this ? (y/n) - "
   [ "$YN" = "N" ] && abort

   echo
   echo "Cleaning MBR..."
   dd if=/bin/clean.mbr of=$device count=1 || { echo "Error Cleaning MBR"; abort; }

   cyl=$((($mbs*1024*1024)/($head*$sect*512)))
   command="0,$cyl,b,*"

   [ "$use_cache" = "yes" ] && { cache_par="$device"2; cyl_cache=$((($mbs_cache*1024*1024)/($head*$sect*512))); command="$command\n,$cyl_cache,83,"; }
   
   echo $command
   echo
   echo "[0;33m             ======================================[0m"
   echo "[0;33m              Create partition tables on $device...[0m"
   echo "[0;33m             ======================================[0m"
   echo -e $command | sfdisk -q $device || { echo "Error Partitioning "; abort; }
   echo
   echo "[0;33m         =================================================[0m"
   echo "[0;33m          Creating FAT32 file system on primary partition[0m "
   echo "[0;33m         =================================================[0m"
   mkdosfs $boot_par || { echo "Error Creating DOS file system"; abort; }
 
   if [ "$use_cache" = "yes" ]; then
      echo
      echo "[0;33m            =======================================================[0m"
      echo "[0;33m             Creating Linux file system on second partition...[0m"
      echo "[0;33m            =======================================================[0m"
      /bin/mke2fs $cache_par -F -m 0 -i 16384 -b 4096 || { echo "Error Creating LINUX file system ext2 on second partition"; abort; }
      case "$type_cache_par" in
        ext2 )
           echo "[0;33m               =============================================[0m"
           echo "[0;33m                Adjust tunable filesystem parameters on ext2[0m"
           echo "[0;33m               =============================================[0m"
           /bin/tune2fs -f -c 0 -i 0 $cache_par
           ;;
        ext3 )
           echo "[0;33m              ===================================================[0m"
           echo "[0;33m               Creating Linux journaling on second partition and[0m"
           echo "[0;33m                 adjust tunable filesystem parameters on ext3[0m"
           echo "[0;33m              ===================================================[0m"
           /bin/tune2fs -f -c 0 -i 0 -j -O dir_index,has_journal -o journal_data_writeback $cache_par 
           ;;
      esac
   echo "[0;33m           =======================================================[0m"
   echo "[0;33m            Check, fix and optimize directories in filesystem ...[0m"
   echo "[0;33m           =======================================================[0m"
   /bin/e2fsck -yfD $cache_par
   case "$?" in
     "0"|"1"|"2" )
            echo "Done." ;;
    "4"|"8"|"32" )
            echo "[0;31mOne or more errors as occurred. Running e2fsck a manual options:[0m"
            /bin/e2fsck -fD $cache_par ;;
      "16"|"128" ) 
             echo "[0;31mERROR![0m Please, restart the system and try install again."
             echo "If this not solve this error, please analize your disk or replace this."
             abort ;;
   esac  
   echo
   fi
else
   echo "READY TO GO !!!"
   echo "This system will be upgraded now."
   echo
   check_yn "Are you sure you want to do this ? (y/n) - "
   [ "$YN" = "N" ] && abort
fi
 
echo
echo "Installing Boot Loader0..."
syslinux -s $boot_par || { echo "Error installing Syslinux"; abort; }
 
echo
echo "Mounting the new partition"
mount -t vfat $boot_par /mnt || { echo "Error mounting new partition"; abort; }

sync

echo
echo "Copying Files. Please wait..."

if [ "$upgrade_addons" = "yes" ]; then
   cp $INSTDIR/oldpacks/* /mnt > /dev/null 2&>1
else
   [ -e $INSTDIR/pkg.list2 ] && cat $INSTDIR/pkg.list2 | while read f; do
                                                               [ -n "$f" ] && rm -rf /mnt/$f.tgz
                                                         done;
fi

if [ "$have_obsolete" = "yes" ]; then
   [ -e $INSTDIR/pkg.list3 ] && cat $INSTDIR/pkg.list3 | while read f; do
                                                               [ -n "$f" ] && rm -rf /mnt/$f.tgz
                                                         done;
fi

cp $INSTDIR/temp/* /mnt > /dev/null 2&>1
mkdir /mnt/config > /dev/null 2&>1
cp -a $INSTDIR/temp/config/* /mnt/config > /dev/null 2&>1

if [ "$upgrade" = "yes" ]; then
   cp -a $INSTDIR/upgrade/* /mnt/config > /dev/null 2&>1
   [ -e $INSTDIR/ssh_keys.tgz ] && cp $INSTDIR/ssh_keys.tgz /mnt
fi
sync

umount $INSTDIR > /dev/null 2&>1
rm -rf $INSTDIR
umount /mnt
echo
echo
echo
echo "[0;33m*******************  Done. **********************[0m"
echo
echo
echo
echo "Your instalation is done."
echo
echo "Remove any instalation CD from your drives"
echo "Set the BIOS to boot from device installed on $iface"
echo
check_yn "Reboot the system now ? (y/n) - "
if [ "$YN" = "Y" ]; then
   touch /tmp/reboot
   reboot
fi
