cat << CLEOF
<body><table class=maintable border=0 cellspacing=1 width=100%>
<tr><td width=160>
 <a href=http://www.smartrouter.com.br><img border=0 src="/brasao.png" width="150" height="100"></a></td>
 <td class=tdbfw><span id=textbfw>SmartRouter PROJECT</span><br>
 <a href=http://www.smartrouter.com.br>http://www.smartrouter.com.br</a></td>
</tr><tr><td valign="top"><table class=menutable><tr><th>$MM</th></tr>
CLEOF
