cat << CLEOF
<body>
<table class=maintable border=0 cellspacing=1 width=100%>
<tr>
 <td class=tdbfw colspan=2>
	 <div align="center">
	 	<img src="/brasao.png" align="left">
		<div style="float: left;width: 70%;"><br clear="right"><br clear="right"><br clear="right">
			<span id=textbfw>SmartRouter PROJECT</span><br clear="right">A GNU/Linux Router, Firewall and Proxy Server<br clear="right">
			<a href=http://www.smartrouter.com.br>http://www.smartrouter.com.br</a>
		</div>
		<div align="right"><br>
		<form target="paypal" action="https://www.paypal.com/cgi-bin/webscr" method="post" style="display: inline; margin: 0px; padding: 0px;float: right;">
			<input type="hidden" name="cmd" value="_s-xclick">
			<input type="hidden" name="hosted_button_id" value="K26H8U8S6GW9Q">
			<input type="image" style="padding: 0px;" src="/imagens_doacao/paypal.gif" name="submit">
		</form>
		<form target="pagseguro" action="https://pagseguro.uol.com.br/checkout/doacao.jhtml" method="post" style="display: inline; margin: 0px; padding: 0px;float: right;">
			<input type="hidden" name="email_cobranca" value="smartrouter.project@gmail.com">
			<input type="hidden" name="moeda" value="BRL">
			<input type="image" style="padding: 0px;" src="/imagens_doacao/pagseguro.gif" name="submit">
		</form>
		</align>
	 </div>
 </td>
</tr>
<tr>
 <td valign="top">
 <table class=menutable width=152>
	<tr>
	 <th>$MM</th>
	</tr>
