echo "
<body>
<table class=maintable border=0 cellspacing=1 width=100%>
<tr>
 <td class=tdbfw colspan=2>
	 <div align="center">
	 <img src="/brasao.png" align="left"><br clear="right"><br clear="right"><br clear="right">
	 <span id=textbfw>SmartRouter PROJECT</span><br clear="right">A GNU/Linux Router, Firewall and Proxy Server<br clear="right">
	 <a href=http://www.smartrouter.com.br>http://www.smartrouter.com.br</a>
	 </div>
 </td>
</tr>
<tr>
 <td valign="top">
 <table class=menutable width=152>
	<tr>
	 <th>$MM</th>
	</tr>"